### ISSUE TITLE
Auto Refreshed when Enter Pressed

### ISSUE THREAD

**Issue by abbayosua** [abbayosua/glintstodo#1]
https://github.com/abbayosua/glintstodo/blob/48dabfca320d60adb2a8b23607df0ad9bf02b645/index.html#L32

i've put form tag on input and button. it works when we pressed enter but the page are refreshed itself.

@mhaidarh

**Comment by mhaidarhanif** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault

https://www.w3schools.com/jsref/event_preventdefault.asp

**Comment by abbayosua** [comment]
Thanks
